gluster:
  hosts:
    rock4:
      disks:
        - dev: sda1
          brick: /bricks/brick-rock4-a
        - dev: sdb1
          brick: /bricks/brick-rock4-b
        - dev: sdc1
          brick: /bricks/brick-rock4-c
        - dev: sdd1
          brick: /bricks/brick-rock4-d
    rock5:
      disks:
        - dev: nvme0n1p1
          brick: /bricks/brick-rock5
