gluster:
  hosts:
    rock4:
      disks:
        - dev: sda1
          brick: /bricks/brick-rock4-a
          format: ext4
        - dev: sdb1
          brick: /bricks/brick-rock4-b
          format: ext4
        - dev: sdc1
          brick: /bricks/brick-rock4-c
          format: ext4
        - dev: sdd1
          brick: /bricks/brick-rock4-d
          format: ext4
    rock5:
      disks:
        - dev: nvme0n1p1
          brick: /bricks/brick-rock5-a
          format: ext4
        - dev: nvme0n1p2
          brick: /bricks/brick-rock5-b
          format: ext4
    node1:
      disks:
        - dev: sda
          brick: /bricks/brick-node1-a
          format: xfs
    node3:
      disks:
        - dev: sda
          brick: /bricks/brick-node3-a
          format: xfs
        - dev: sdb
          brick: /bricks/brick-node3-b
          format: xfs
