---
- name: Ensure gluster packages installed and started
  ansible.builtin.include_tasks: roles/glusterfs/tasks/packages.yml

- name: Ensure bricks set up
  ansible.builtin.include_tasks: roles/glusterfs/tasks/bricks.yml

- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ gluster_cluster_hosts }}"

- name: Check if volume exists
  ansible.builtin.shell: |
    gluster volume list
  register: vol_list

- name: Debug vol_list
  ansible.builtin.debug:
    var: vol_list.stdout
# - name: Create main gluster volume
#   ansible.builtin.shell: |
#     gluster volume create {{ volume_name }} disperse 3 {{ bricks }} force
#   when: volume_name not in vol_list.stdout

# - name: Start main gluster volume
#   gluster.gluster.gluster_volume:
#     state: started
#     name: main

- name: Enable automount of GlusterFS
  ansible.posix.mount:
    path: /mnt/{{ volume_name }}
    src: localhost:/{{ volume_name }}
    fstype: glusterfs
    opts: defaults,_netdev 0 0
    state: present

- name: Mount GlusterFS
  ansible.posix.mount:
    path: /mnt/{{ volume_name }}
    src: localhost:/{{ volume_name }}
    fstype: glusterfs
    opts: defaults,_netdev 0 0
    state: mounted
